# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p3B8fWRNIS55raVtbFQWG_onf2JQb-SG
"""

CONFIG = {
    'device': torch.device('cuda' if torch.cuda.is_available() else 'cpu'),
    'batch_size': 256,
    'lr': 1e-4,
    'z_dim': 8,

    # TUNED HYPERPARAMETERS
    'pretrain_epochs': 50,
    'n_fim_samples': 10000,

    'forget_steps': 10000,
    'lmbda': 100000,

    'gamma': 1.0,
    'label_to_drop': 0
}

print(f"Running on: {CONFIG['device']}")