# -*- coding: utf-8 -*-
"""Entanglement_visualiziation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FyCuenWMk_dR58fRuXxvX_vWtR_lTXX0
"""

import torch
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
import umap
from torchvision import datasets, transforms

from config import CONFIG


def get_latent_data_blind(vae, dataloader, num_samples=10000): # CHANGED: 2000 -> 10000
    vae.eval()
    zs = []
    ys = []
    with torch.no_grad():
        for x, y in dataloader:
            x = x.to(CONFIG['device'])

            # Blind the encoder (Feed Zeros)
            batch_size = x.size(0)
            y_blind = torch.zeros(batch_size, 10).float().to(CONFIG['device'])

            mu, log_var = vae.encoder(x.view(-1, 784), y_blind)
            z = vae.sampling(mu, log_var)

            zs.append(z.cpu().numpy())
            ys.append(y.numpy())

            if len(np.concatenate(zs)) >= num_samples:
                break

    return np.concatenate(zs)[:num_samples], np.concatenate(ys)[:num_samples]


def plot_scatter_separated(vae, title_suffix):
    print(f"Generating High-Density Scatter Plots for {title_suffix}...")

    # Get data
    dataset = datasets.MNIST(root='./data', train=False, transform=transforms.ToTensor())
    loader = torch.utils.data.DataLoader(dataset, batch_size=1000, shuffle=True)

    # Get 10,000 samples for that dense look
    z, y = get_latent_data_blind(vae, loader, num_samples=10000)

    fig, axes = plt.subplots(1, 2, figsize=(20, 9)) # Bigger figure

    # t-SNE
    print("Running t-SNE (This may take a moment)...")
    # perplexity=50 often helps separate clusters better
    tsne = TSNE(n_components=2, random_state=42, perplexity=50, n_iter=1000)
    z_tsne = tsne.fit_transform(z)

    sc1 = axes[0].scatter(z_tsne[:, 0], z_tsne[:, 1], c=y, cmap='tab10',
                          alpha=0.5, s=2) # Smaller dots (s=2), higher transparency
    axes[0].set_title(f"t-SNE (Blind): {title_suffix}")
    fig.colorbar(sc1, ax=axes[0], ticks=range(10))

    # UMAP
    print("Running UMAP...")
    # n_neighbors=15 (local structure), min_dist=0.1 (tight packing)
    reducer = umap.UMAP(n_neighbors=30, min_dist=0.0, random_state=42)
    z_umap = reducer.fit_transform(z)

    sc2 = axes[1].scatter(z_umap[:, 0], z_umap[:, 1], c=y, cmap='tab10',
                          alpha=0.5, s=2) # Smaller dots
    axes[1].set_title(f"UMAP (Blind): {title_suffix}")
    fig.colorbar(sc2, ax=axes[1], ticks=range(10))

    plt.show()