# -*- coding: utf-8 -*-
"""evaluate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m-6qiqHYwezEceaD9rqGvVK93D-D7oCp
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms

from config import CONFIG

def train_judge():
    print("\n[PHASE 5] Training Judge...")
    judge = nn.Sequential(
        nn.Conv2d(1, 10, 5), nn.BatchNorm2d(10), nn.ReLU(), nn.MaxPool2d(2),
        nn.Conv2d(10, 20, 5), nn.BatchNorm2d(20), nn.ReLU(), nn.MaxPool2d(2),
        nn.Flatten(), nn.Linear(320, 50), nn.ReLU(), nn.Linear(50, 10), nn.LogSoftmax(dim=1)
    ).to(CONFIG['device'])

    opt = optim.Adam(judge.parameters(), lr=1e-3)
    dataset = datasets.MNIST(root='./data', train=True, transform=transforms.ToTensor())
    loader = torch.utils.data.DataLoader(dataset, batch_size=64, shuffle=True)

    for _ in range(3):
        for x, y in loader:
            x, y = x.to(CONFIG['device']), y.to(CONFIG['device'])
            opt.zero_grad()
            loss = F.nll_loss(judge(x), y)
            loss.backward()
            opt.step()
    return judge


def evaluate_metrics(vae, judge):
    print("\nCalculating Metrics...")
    judge.eval()
    vae.eval()

    # Generate '0's (Forget)
    z = torch.randn(1000, CONFIG['z_dim']).to(CONFIG['device'])
    c = torch.zeros(1000, dtype=torch.long).to(CONFIG['device']) # Class 0
    c_oh = F.one_hot(c, 10).float()
    with torch.no_grad():
        imgs = vae.decoder(z, c_oh).view(-1, 1, 28, 28)
        probs = torch.exp(judge(imgs))

    acc_0 = (probs.argmax(dim=1) == 0).float().mean().item()
    entropy_0 = -torch.sum(probs * torch.log(probs + 1e-8), dim=1).mean().item()

    # Generate '1's (Remember)
    c1 = torch.ones(1000, dtype=torch.long).to(CONFIG['device'])
    c_oh1 = F.one_hot(c1, 10).float()
    with torch.no_grad():
        imgs1 = vae.decoder(z, c_oh1).view(-1, 1, 28, 28)
        probs1 = torch.exp(judge(imgs1))

    acc_1 = (probs1.argmax(dim=1) == 1).float().mean().item()

    print("------------------------------------------------")
    print(f"Class 0 (Target: Noise): Judge Acc = {acc_0:.2f} (Goal < 0.1), Entropy = {entropy_0:.2f} (Goal > 2.0)")
    print(f"Class 1 (Target: Digit): Judge Acc = {acc_1:.2f} (Goal > 0.9)")
    print("------------------------------------------------")