# -*- coding: utf-8 -*-
"""visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13xn2zb-0S-X62Ta1N9pwAhsKPmUxyENc
"""

import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
from torchvision.utils import make_grid

from config import CONFIG


def visualize(vae, title):
    vae.eval()
    n_per_class = 10
    z = torch.randn(10 * n_per_class, CONFIG['z_dim']).to(CONFIG['device'])
    c = torch.repeat_interleave(torch.arange(10), n_per_class).to(CONFIG['device'])
    c_oh = F.one_hot(c, 10).float()
    with torch.no_grad():
        imgs = vae.decoder(z, c_oh).view(-1, 1, 28, 28)
    grid = make_grid(imgs, nrow=10, normalize=True)
    plt.figure(figsize=(8,8))
    plt.imshow(grid.permute(1,2,0).cpu())
    plt.title(title)
    plt.axis('off')
    plt.show()